[general]
import = [
    # "~/.local/share/alacritty/alacritty-theme/themes/gruvbox_dark.toml",
    "~/.local/share/alacritty/alacritty-theme/themes/github_light.toml",
    # "~/.local/share/alacritty/alacritty-theme/themes/tokyo-night.toml",
]

[terminal]
shell = { program = "/usr/bin/bash", args = ["-c", "tmux attach || tmux new -t main"] }

[window]
decorations = "Full"
# decorations_theme_variant = "Dark"
padding = { x = 5, y = 5 }
dynamic_title = true
dimensions = { columns = 120, lines = 40 }

[font]
normal = { family = "CaskaydiaCove NF" }
size = 11

[env]
term = "xterm-256color"
