[shell]
program = '/usr/bin/bash'
args = ['-c', 'tmux attach || tmux new -t main']


[window]
decorations = 'Full'
padding = { x = 5, y = 5}

[font]
normal = { family = 'FiraCode Nerd Font Mono' }
size = 12.0
