import = [
    "~/dotfiles/alacritty/.config/alacritty/themes/themes/kanagawa_dragon.toml",
]

[shell]
program = '/usr/bin/bash'
args = ['-c', 'tmux attach || tmux new -t main']


[window]
decorations = 'Full'
padding = { x = 5, y = 5}
dynamic_title = true
dimensions = { columns = 120, lines = 40} 
decorations_theme_variant = 'Dark'

[font]
normal = { family = 'FiraCode Nerd Font Mono' }
size = 11.0
