-- vim.fn.sign_define("DiagnosticSignError", { text = " ", texthl = "DiagnosticSignError" })
-- vim.fn.sign_define("DiagnosticSignWarn", { text = " ", texthl = "DiagnosticSignWarn" })
-- vim.fn.sign_define("DiagnosticSignInfo", { text = " ", texthl = "DiagnosticSignInfo" })
-- vim.fn.sign_define("DiagnosticSignHint", { text = "󰌵", texthl = "DiagnosticSignHint" })
--
-- require('neo-tree').setup({
--     opts = {
--         sources = { "filesystem", "buffers", "git_status", "document_symbols" },
--         open_files_do_not_replace_types = { "terminal", "Trouble", "trouble", "qf", "Outline" },
--         filesystem = {
--             bind_to_cwd = false,
--             follow_current_file = { enabled = true },
--             use_libuv_file_watcher = true,
--         },
--         window = {
--             mappings = {
--                 ["<space>"] = "none",
--             },
--         },
--         default_component_configs = {
--             indent = {
--                 with_expanders = true, -- if nil and file nesting is enabled, will enable expanders
--                 expander_collapsed = "",
--                 expander_expanded = "",
--                 expander_highlight = "NeoTreeExpander",
--             },
--         },
--     },
-- })
