import = [
	"~/.dotfiles/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
]

[shell]
program = '/usr/bin/bash'
args = ['-c', 'tmux attach || tmux new -t main']

[window]
# decorations = 'Full'
decorations = 'None'
padding = { x = 5, y = 5 }
dynamic_title = true
dimensions = { columns = 120, lines = 40 }
decorations_theme_variant = 'Dark'

[font]
normal = { family = 'ComicShannsMono Nerd Font' }
size = 9
